{"name": "test_Login_with_valid_credential", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('setup_and_teardown', <FixtureRequest for <Function test_Login_with_valid_credential>>)", "trace": "file C:\\Users\\RAGHU\\pythonmultifile\\Pytestproject\\PytestPython\\Test_Login.py, line 8\n   def test_Login_with_valid_credential(self):\nE       fixture 'setup_and_teardown' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, log_on_failure, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\RAGHU\\pythonmultifile\\Pytestproject\\PytestPython\\Test_Login.py:8"}, "start": 1720022984100, "stop": 1720022984100, "uuid": "55c1057e-c9fa-4c1b-af71-41f6fbc0b916", "historyId": "ca5b919cab68eebe35d98aa0fa56ffcd", "testCaseId": "ca5b919cab68eebe35d98aa0fa56ffcd", "fullName": "PytestPython.Test_Login.TestLogin#test_Login_with_valid_credential", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "PytestPython"}, {"name": "suite", "value": "Test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "RAGHU"}, {"name": "thread", "value": "26808-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "PytestPython.Test_Login"}]}